#Planet Scale DB (mysql 8)
#spring:
#  datasource:
#    url: jdbc:mysql://ap-northeast.connect.psdb.cloud/local-test?sslMode=VERIFY_IDENTITY
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: 8cip3dmicivw3j8xigsw
#    username: ${DB_USER}
#    password: pscale_pw_ehDfKrNdFGrzhp27B4IDK155qV4OIuZ5npNV2WeZVzd
#    password: ${DB_PASSWORD}

# docker-compose yml
#spring:
#  datasource:
#    url: jdbc:mariadb://${MARIADB_ADDRESS}:3306/testdb
#    driver-class-name: org.mariadb.jdbc.Driver
#    username: ${MARIADB_USERNAME}
#    password: ${MARIADB_PASSWORD}

# docker-single-container yml
spring:
  datasource:
    url: jdbc:mysql://springstudy.cgllngfx5zdm.ap-northeast-2.rds.amazonaws.com:3306/changedworld
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 30

  jpa:
    generate-ddl: true
    hibernate: # create: drop-create
      ddl-auto: update
      show-sql: true
#      naming:
#        naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
jwt:
  secret: thisissecretkey01294809180@@12120980@@12120980